on:
  workflow_dispatch:

jobs:
  build_macos:
    runs-on: macos-latest
    steps:
      - name: Install DotNet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x
            10.0.x

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          brew install \
          cmake \
          ninja
          
      - name: Build Third Party Libraries
        run: |
          cd ./ThirdParty/
          dotnet run build_and_copy_all_third_party.cs -- Release

      - name: Build First Party Native Lib
        run: |
          cd ./TinyFFR.Native/build/
          dotnet run build.cs -- Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: native_libs_macos
          path: | 
            build_output/Release/libassimp*
            build_output/Release/libSDL*
            !build_output/Release/libSDL2_test*
            build_output/Release/libTinyFFR*
        

      

  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install DotNet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x
            10.0.x
    
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            build-essential \
            libglu1-mesa-dev \
            ninja-build \
            libc++-dev \
            libc++abi-dev \
            clang-18 \
            libc++-18-dev \
            libc++abi-18-dev \
            mesa-common-dev \
            libxi-dev \
            libxxf86vm-dev \
            libgl1-mesa-dev \
            libgles2-mesa-dev \
            libegl1-mesa-dev \
            libwayland-dev \
            libxkbcommon-dev \
            wayland-protocols \
            libgl1-mesa-dev
          sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-18 100

      - name: Build Third Party Libraries
        run: |
          cd ./ThirdParty/
          dotnet run build_and_copy_all_third_party.cs -- Release

      - name: Build First Party Native Lib
        run: |
          cd ./TinyFFR.Native/build/
          dotnet run build.cs -- Release

      - name: Copy Clang/LLVM Runtime to Build Output
        run: | 
          cp -L "/usr/lib/x86_64-linux-gnu/libc++.so.1" "build_output/Release/"
          cp -L "/usr/lib/x86_64-linux-gnu/libc++abi.so.1" "build_output/Release/"
          cp -L "/usr/lib/x86_64-linux-gnu/libunwind.so.1" "build_output/Release/"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: native_libs_linux
          path: | 
            build_output/Release/libassimp*
            build_output/Release/libSDL*
            !build_output/Release/libSDL2_test*
            build_output/Release/libTinyFFR*
            build_output/Release/libc++*
            build_output/Release/libunwind*


  build_windows:
    runs-on: windows-latest
    steps:
      - name: Install DotNet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x
            10.0.x

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Build Third Party Libraries
        run: |
          cd ./ThirdParty/
          dotnet run build_and_copy_all_third_party.cs -- Release

      - name: Build First Party Native Lib
        run: |
          cd ./TinyFFR.Native/build/
          dotnet run build.cs -- Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: native_libs_windows
          path: | 
            build_output/Release/assimp*
            build_output/Release/SDL2*
            !build_output/Release/SDL2_test*
            build_output/Release/TinyFFR*

  create_nupkgs:
    runs-on: windows-latest
    needs:
      - build_windows
      - build_macos
      - build_linux
    steps:
      - name: Install DotNet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x

      - name: Checkout
        uses: actions/checkout@v4
           
      - name: Download MacOS Native Libs
        uses: actions/download-artifact@v4
        with:
          name: native_libs_macos
          path: ./Publishing/TinyFFR.NuGet/prebuilt_binaries/osx-arm64/

      - name: Download Linux Native Libs
        uses: actions/download-artifact@v4
        with:
          name: native_libs_linux
          path: ./Publishing/TinyFFR.NuGet/prebuilt_binaries/linux-x64/

      - name: Download Windows Native Libs
        uses: actions/download-artifact@v4
        with:
          name: native_libs_windows
          path: ./Publishing/TinyFFR.NuGet/prebuilt_binaries/win-x64/

      - name: Build Main Lib
        run: |
          cd ./TinyFFR/
          dotnet restore
          dotnet build -c Release --no-restore

      - name: Build Avalonia Lib
        run: |
          cd ./Integrations/TinyFFR.Avalonia/
          dotnet restore
          dotnet build -c Release --no-restore

      - name: Build WPF Lib
        run: |
          cd ./Integrations/TinyFFR.Wpf/
          dotnet restore
          dotnet build -c Release --no-restore

      - name: Build WinForms Lib
        run: |
          cd ./Integrations/TinyFFR.WinForms/
          dotnet restore
          dotnet build -c Release --no-restore

      - name: Build Main Nuget Package
        run: | 
          cd ./Publishing/TinyFFR.NuGet/
          dotnet restore
          dotnet pack -c Release --no-build --no-restore

      - name: Build Avalonia Nuget Package
        run: | 
          cd ./Publishing/TinyFFR.Avalonia.NuGet/
          dotnet restore
          dotnet pack -c Release --no-build --no-restore

      - name: Build WPF Nuget Package
        run: | 
          cd ./Publishing/TinyFFR.Wpf.NuGet/
          dotnet restore
          dotnet pack -c Release --no-build --no-restore

      - name: Build WinForms Nuget Package
        run: | 
          cd ./Publishing/TinyFFR.WinForms.NuGet/
          dotnet restore
          dotnet pack -c Release --no-build --no-restore

      - name: Upload Nuget Packages
        uses: actions/upload-artifact@v4
        with:
          name: nuget_packages
          path: | 
            ./Publishing/TinyFFR.NuGet/build_output/*.nupkg
            ./Publishing/TinyFFR.Avalonia.NuGet/build_output/*.nupkg
            ./Publishing/TinyFFR.Wpf.NuGet/build_output/*.nupkg
            ./Publishing/TinyFFR.WinForms.NuGet/build_output/*.nupkg
 
